import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Michael&apos;s NextJS Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Michael&apos;s NextJS Playground</h1>
      </main>

      <footer>
        <p>Footer goes here</p>
      </footer>
    </div>
  );
};

export default Home;
